### ISSUE TITLE
No bones about it

### ISSUE THREAD

**Issue by gfixler** [isovector/typecraft#1]
I want to play, but stack commands keep giving me this:

/home/gfixler/bones/: getDirectoryContents:openDirStream: does not exist (No such file or directory)

What is bones?

**Comment by schell** [comment]
I've got a bones to pick with you! ;)

**Comment by isovector** [comment]
Fixed! It's not exactly what you might call a "playable" game yet, but if you want to play around with the pathing visualizer this is the project for YOUUUUU
